
##########################################
#     Change these variables !important
##########################################

# Set this for Copyright in the footer
owner: Benjamin Levinson

# Optional social-links in the footer
# To disable set enable to false
links:
  enable: true

# Set this to your main site title. If page doesn't have its own title,
# then this title will be used.
title: Ben Levinson


# Following needed for disqus integration
# Set your 'disqus' account name
disqus:

# Uncomment if deployed locally
url: https://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
#url: https://blevinson19.github.io

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
# NOTE! only change if site is NOT in master's branch
baseurl:

# Change this to your google analytics ID
google_analytics:

# Contact form pupublic key
contact_PK: c44344d4c57a1c0a08b46feb875ef50e

##########################################
#          Optional variables
##########################################

# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# MathJax support
math: true

collections:
- definitions

github_username:  blevinson19
email: benjaminlevinson2019@u.northwestern.edu


##########################################
#          P5.js Setup
##########################################
p5:
  - p5
  - addons/p5.sound
  - addons/p5.dom
sketches:
  - setup_p5


##########################################
#          Do not change these variables
##########################################

include:
  - _pages

sass:
  sass_dir: _sass
sass:
    style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file

paginate_path: /_pages/page:num

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
